@startuml act_diagram
|User|
start
    repeat
    :see the main page;
    if(choose login or register) is (login) then
        repeat
        :login with user and password;
        |System|
        :search user>
        |Database|
        :search user<
        if(user and password found?) is (yes) then
        :correct user and password>
        |System|
        :correct user and password<
        :show my texts page;
        |User|
        while ()
        switch (choose activity)
            case (new encrypt text)
                :enter a text with a key;
                |System|
                :encrypt text with the key;
                :save text>
                |Database|
                :save text<
                |System|
                :show encrypted text>
                |User|
                label sp_lab1

            case (decrypt text)
                :enter key;
                :push decrypt button;
                |System|
                :check key>
                |Database|
                :check key<
                |System|
                :check key>
                :show decrypted text;
                |User|
                label sp_lab1

            case (encrypt again text)
                |User|
                :push encrypt button;
                |System|
                :show encrypted text;
                |User|
                label sp_lab1
        endswitch
        endwhile (close page)
        |System|
        :close the web page;
        stop
        endif

        ->no;
        :incorrect user and password<
        |System|
        backward: message of error;
        repeat while()
        detach;

    endif
    |User|
    ->register;
    repeat
    :enter user data;
    |System|
    backward: message of error;
    repeat while(check data) is (incorrect) not (correct)
    backward: now login;

    repeat while()




@enduml